[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "git"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["python generate_session.py"]

[start]
cmd = "python railway_start.py" 