services:
  - type: web
    name: telegram-userbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: echo "Este es un userbot de Telegram que debe ejecutarse localmente"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 